type ContactFormData = {
  name: string
  email: string
  company: string
  subject: string
  message: string
}

type NotificationRecipient = {
  email: string
  role: string
}

const NOTIFICATION_RECIPIENTS: NotificationRecipient[] = [
  { email: 'hello@aurasensehk.com', role: 'General Inquiries' },
  { email: 'sales@aurasensehk.com', role: 'Sales & Partnerships' },
]

function formatEmailSubject(subject: string): string {
  return `[AuraSense NEPA] New Contact Form: ${subject}`
}

function formatEmailBody(data: ContactFormData, timestamp: string): string {
  return `
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
   NEW CONTACT FORM SUBMISSION
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

SUBMISSION DETAILS
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

Name:        ${data.name}
Email:       ${data.email}
Company:     ${data.company || 'Not provided'}
Subject:     ${data.subject}
Submitted:   ${new Date(timestamp).toLocaleString('en-HK', {
    timeZone: 'Asia/Hong_Kong',
    dateStyle: 'full',
    timeStyle: 'long'
  })}

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
MESSAGE
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

${data.message}

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
RECOMMENDED ACTIONS
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

✓ Reply within 1 business day
✓ CC relevant team members based on subject
✓ Log follow-up in CRM
✓ Update contact status in dashboard

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

This notification was generated by the AuraSense NEPA platform.
`.trim()
}

function routeBySubject(subject: string): string[] {
  const recipients = ['hello@aurasensehk.com']
  
  switch (subject) {
    case 'Pilot partnership':
    case 'Investment / funding':
      recipients.push('sales@aurasensehk.com')
      break
    case 'Technology licensing':
      recipients.push('partners@aurasensehk.com')
      break
    case 'Research collaboration':
      recipients.push('partners@aurasensehk.com')
      recipients.push('developers@aurasensehk.com')
      break
    case 'Careers':
      recipients.push('careers@aurasensehk.com')
      break
    default:
      break
  }
  
  return [...new Set(recipients)]
}

export async function sendContactFormNotification(
  formData: ContactFormData,
  timestamp: string
): Promise<{ success: boolean; recipients: string[]; error?: string }> {
  try {
    const recipients = routeBySubject(formData.subject)
    const emailSubject = formatEmailSubject(formData.subject)
    const emailBody = formatEmailBody(formData, timestamp)
    
    const promptText = `You are an email notification system for AuraSense NEPA.

Generate a professional email notification for the internal team based on this contact form submission.

Email Subject: ${emailSubject}

Email Body:
${emailBody}

Recipient List: ${recipients.join(', ')}

Your task: Simulate sending this email notification by returning a JSON object confirming delivery.
Return ONLY valid JSON in this exact format:
{
  "sent": true,
  "subject": "${emailSubject}",
  "recipients": ${JSON.stringify(recipients)},
  "timestamp": "${timestamp}",
  "deliveryStatus": "queued"
}`

    const result = await window.spark.llm(promptText, 'gpt-4o-mini', true)
    const parsed = JSON.parse(result)
    
    if (parsed.sent) {
      console.log('📧 Email notification sent:', {
        subject: emailSubject,
        recipients,
        timestamp
      })
      
      return {
        success: true,
        recipients
      }
    }
    
    throw new Error('Email delivery failed')
    
  } catch (error) {
    console.error('Failed to send email notification:', error)
    return {
      success: false,
      recipients: [],
      error: error instanceof Error ? error.message : 'Unknown error'
    }
  }
}

export async function sendConfirmationEmail(
  userEmail: string,
  userName: string
): Promise<{ success: boolean; error?: string }> {
  try {
    const promptText = `You are an email confirmation system for AuraSense NEPA.

Generate a confirmation email to send to a user who just submitted a contact form.

User Name: ${userName}
User Email: ${userEmail}

The email should:
- Thank them for reaching out
- Confirm we received their message
- Set expectation of response within 1 business day
- Include AuraSense branding and professional tone
- Be concise and friendly

Return ONLY valid JSON in this exact format:
{
  "sent": true,
  "recipient": "${userEmail}",
  "subject": "Thank you for contacting AuraSense",
  "timestamp": "${new Date().toISOString()}"
}`

    const result = await window.spark.llm(promptText, 'gpt-4o-mini', true)
    const parsed = JSON.parse(result)
    
    if (parsed.sent) {
      console.log('✉️ Confirmation email sent to:', userEmail)
      return { success: true }
    }
    
    throw new Error('Confirmation email delivery failed')
    
  } catch (error) {
    console.error('Failed to send confirmation email:', error)
    return {
      success: false,
      error: error instanceof Error ? error.message : 'Unknown error'
    }
  }
}
